name: 'rhub-platform-info'
description: |
  R platform information.
author: 'Gábor Csárdi'

inputs:
  token:
    description: |
      Custom GitHub personal access token. Useful to allow access to
      private repositories or other resources.
  job-config:
    description: |
      The matrix config, as set up by the r-hub-setup action.

runs:
  using: "composite"
  steps:
  - name: R Options
    run: |
      #
      cat("::group::R Options\n")
      options()
      cat("::endgroup::\n")
    shell: Rscript {0}

  - name: Environment variables in R
    run: |
      #
      cat("::group::Environment variables in R\n")
      Sys.getenv()
      cat("::endgroup::\n")
    shell: Rscript {0}

  - name: OS information
    run: |
      #
      cat("::group::OS information\n")
      if (Sys.info()[["sysname"]] == "Linux") {
        writeLines("-- uname -a -------------------------------------------------------------")
        system("uname -a")
        if (file.exists("/etc/os-release")) {
          writeLines("-- /etc/os-release ------------------------------------------------------")
          writeLines(readLines("/etc/os-release"))
        }
      } else if (Sys.info()[["sysname"]] == "Darwin") {
        writeLines("-- macOS system info ----------------------------------------------------")
        system("system_profiler SPSoftwareDataType SPHardwareDataType")
      } else if (Sys.info()[["sysname"]] == "Windows") {
        writeLines("-- Windows system info --------------------------------------------------")
        system("systeminfo")
      }
      cat("::endgroup::\n")
    shell: Rscript {0}

  - name: Compiler information
    run: |
      #
      cat("::group::Compiler information\n")
      writeLines("-- $(CC) --version ------------------------------------------------------")
      invisible(system(paste(system(paste0(file.path(R.home("bin"), "R"), " CMD config CC"), intern = TRUE), "--version")))
      writeLines("-- $(CXX) --version  ----------------------------------------------------")
      invisible(system(paste(system(paste0(file.path(R.home("bin"), "R"), " CMD config CXX"), intern = TRUE), "--version")))
      writeLines("-- $(FC) --version ------------------------------------------------------")
      invisible(system(paste(system(paste0(file.path(R.home("bin"), "R"), " CMD config FC"), intern = TRUE), "--version")))
      cat("::endgroup::\n")
    shell: Rscript {0}

  - name: R session information
    run: |
      #
      cat("::group::R session information\n")
      sessionInfo()
      cat("::endgroup::\n")
    shell: Rscript {0}

  - name: More R infomation
    run: |
      #
      cat("::group::More R information\n")
      writeLines("-- capabilities() -------------------------------------------------------")
      capabilities()
      writeLines("-- extSoftVersion() -----------------------------------------------------")
      extSoftVersion()
      writeLines("-- l10n_info() ----------------------------------------------------------")
      l10n_info()
      writeLines("-- La_version(), La_library() -------------------------------------------")
      La_version()
      La_library()
      writeLines("-- grSoftVersion() ------------------------------------------------------")
      grSoftVersion()
      writeLines("-- pcre_config() --------------------------------------------------------")
      pcre_config()
      writeLines("-- libcurlVersion() -----------------------------------------------------")
      libcurlVersion()
      cat("::endgroup::\n")
    shell: Rscript {0}

  - name: R CMD config
    run: |
      #
      cat("::group::R CMD config\n")
      system(paste0(file.path(R.home("bin"), "R"), " CMD config --all"))
      cat("::endgroup::\n")
    shell: Rscript {0}
